/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
#define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
#define _NAMESPACE_CONCAT(NS, ID) NS ## ID
#define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
#define CASADI_PREFIX(ID) FORCESNLPsolver_basic_3_20_50_1_model_20_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "FORCESNLPsolver_basic_3_20_50_1/include/FORCESNLPsolver_basic_3_20_50_1.h"

#define PRINTF printf
FORCESNLPsolver_basic_3_20_50_1_float CASADI_PREFIX(sq)(FORCESNLPsolver_basic_3_20_50_1_float x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

FORCESNLPsolver_basic_3_20_50_1_float CASADI_PREFIX(sign)(FORCESNLPsolver_basic_3_20_50_1_float x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const solver_int32_default CASADI_PREFIX(s0)[] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
#define s0 CASADI_PREFIX(s0)
static const solver_int32_default CASADI_PREFIX(s1)[] = {42, 1, 0, 42, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41};
#define s1 CASADI_PREFIX(s1)
static const solver_int32_default CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const solver_int32_default CASADI_PREFIX(s3)[] = {1, 15, 0, 1, 2, 3, 3, 4, 5, 6, 7, 8, 8, 8, 8, 8, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const solver_int32_default CASADI_PREFIX(s4)[] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
#define s4 CASADI_PREFIX(s4)
static const solver_int32_default CASADI_PREFIX(s5)[] = {6, 15, 0, 0, 0, 0, 0, 3, 6, 10, 14, 18, 18, 18, 18, 18, 18, 18, 0, 1, 2, 3, 4, 5, 0, 3, 4, 5, 1, 3, 4, 5, 2, 3, 4, 5};
#define s5 CASADI_PREFIX(s5)
/* evaluate_stages */
solver_int32_default FORCESNLPsolver_basic_3_20_50_1_model_20(const FORCESNLPsolver_basic_3_20_50_1_float **arg, FORCESNLPsolver_basic_3_20_50_1_float **res) 
{
    FORCESNLPsolver_basic_3_20_50_1_float a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36,a37,a38,a39,a40,a41,a42,a43,a44,a45,a46,a47,a48,a49,a50,a51,a52,a53,a54,a55,a56,a57,a58,a59,a60,a61,a62,a63,a64,a65,a66,a67,a68,a69,a70,a71,a72,a73,a74,a75,a76,a77,a78,a79,a80,a81,a82,a83,a84,a85;
    a0=arg[1] ? arg[1][7] : 0;
    a1=arg[0] ? arg[0][6] : 0;
    a2=(a0-a1);
    a3=arg[1] ? arg[1][14] : 0;
    a2=(a2*a3);
    a4=(a0-a1);
    a5=(a2*a4);
    a6=arg[1] ? arg[1][8] : 0;
    a7=arg[0] ? arg[0][7] : 0;
    a8=(a6-a7);
    a8=(a8*a3);
    a9=(a6-a7);
    a10=(a8*a9);
    a5=(a5+a10);
    a10=arg[1] ? arg[1][9] : 0;
    a11=arg[0] ? arg[0][8] : 0;
    a12=(a10-a11);
    a12=(a12*a3);
    a13=(a10-a11);
    a14=(a12*a13);
    a5=(a5+a14);
    a14=arg[1] ? arg[1][3] : 0;
    a0=(a0-a14);
    a0=sq(a0);
    a14=arg[1] ? arg[1][4] : 0;
    a6=(a6-a14);
    a6=sq(a6);
    a0=(a0+a6);
    a6=arg[1] ? arg[1][5] : 0;
    a10=(a10-a6);
    a10=sq(a10);
    a0=(a0+a10);
    a10=1.;
    a0=fmax(a0,a10);
    a5=(a5/a0);
    a6=arg[1] ? arg[1][10] : 0;
    a14=arg[0] ? arg[0][14] : 0;
    a6=(a6-a14);
    a14=sq(a6);
    a14=(a3*a14);
    a5=(a5+a14);
    a14=arg[0] ? arg[0][0] : 0;
    a15=2.0943951023931956e-01;
    a14=(a14/a15);
    a16=arg[1] ? arg[1][15] : 0;
    a17=(a14*a16);
    a18=(a17*a14);
    a19=arg[0] ? arg[0][1] : 0;
    a19=(a19/a15);
    a15=(a19*a16);
    a20=(a15*a19);
    a18=(a18+a20);
    a20=arg[0] ? arg[0][2] : 0;
    a21=(a20*a16);
    a22=(a21*a20);
    a18=(a18+a22);
    a22=1.5707963267948966e+00;
    a22=(a20/a22);
    a23=(a22*a16);
    a24=(a23*a22);
    a18=(a18+a24);
    a5=(a5+a18);
    a18=arg[1] ? arg[1][18] : 0;
    a24=(a1-a18);
    a25=sq(a24);
    a26=arg[1] ? arg[1][11] : 0;
    a27=arg[1] ? arg[1][21] : 0;
    a28=(a26+a27);
    a28=sq(a28);
    a25=(a25/a28);
    a29=arg[1] ? arg[1][19] : 0;
    a30=(a7-a29);
    a31=sq(a30);
    a32=arg[1] ? arg[1][12] : 0;
    a33=arg[1] ? arg[1][22] : 0;
    a34=(a32+a33);
    a34=sq(a34);
    a31=(a31/a34);
    a25=(a25+a31);
    a31=arg[1] ? arg[1][20] : 0;
    a35=(a11-a31);
    a36=sq(a35);
    a37=arg[1] ? arg[1][13] : 0;
    a38=arg[1] ? arg[1][23] : 0;
    a39=(a37+a38);
    a39=sq(a39);
    a36=(a36/a39);
    a25=(a25+a36);
    a25=sqrt(a25);
    a36=arg[1] ? arg[1][25] : 0;
    a36=(a25-a36);
    a40=arg[1] ? arg[1][24] : 0;
    a36=(a40*a36);
    a36=exp(a36);
    a41=(a10+a36);
    a42=arg[1] ? arg[1][16] : 0;
    a43=(a42/a41);
    a44=(a43/a41);
    a45=arg[1] ? arg[1][26] : 0;
    a46=(a1-a45);
    a47=sq(a46);
    a48=arg[1] ? arg[1][29] : 0;
    a49=(a26+a48);
    a49=sq(a49);
    a47=(a47/a49);
    a50=arg[1] ? arg[1][27] : 0;
    a51=(a7-a50);
    a52=sq(a51);
    a53=arg[1] ? arg[1][30] : 0;
    a54=(a32+a53);
    a54=sq(a54);
    a52=(a52/a54);
    a47=(a47+a52);
    a52=arg[1] ? arg[1][28] : 0;
    a55=(a11-a52);
    a56=sq(a55);
    a57=arg[1] ? arg[1][31] : 0;
    a58=(a37+a57);
    a58=sq(a58);
    a56=(a56/a58);
    a47=(a47+a56);
    a47=sqrt(a47);
    a56=arg[1] ? arg[1][33] : 0;
    a56=(a47-a56);
    a59=arg[1] ? arg[1][32] : 0;
    a56=(a59*a56);
    a56=exp(a56);
    a60=(a10+a56);
    a61=(a42/a60);
    a62=(a61/a60);
    a63=(a44+a62);
    a64=arg[1] ? arg[1][34] : 0;
    a65=(a1-a64);
    a66=sq(a65);
    a67=arg[1] ? arg[1][37] : 0;
    a68=(a26+a67);
    a68=sq(a68);
    a66=(a66/a68);
    a69=arg[1] ? arg[1][35] : 0;
    a70=(a7-a69);
    a71=sq(a70);
    a72=arg[1] ? arg[1][38] : 0;
    a73=(a32+a72);
    a73=sq(a73);
    a71=(a71/a73);
    a66=(a66+a71);
    a71=arg[1] ? arg[1][36] : 0;
    a74=(a11-a71);
    a75=sq(a74);
    a76=arg[1] ? arg[1][39] : 0;
    a77=(a37+a76);
    a77=sq(a77);
    a75=(a75/a77);
    a66=(a66+a75);
    a66=sqrt(a66);
    a75=arg[1] ? arg[1][41] : 0;
    a75=(a66-a75);
    a78=arg[1] ? arg[1][40] : 0;
    a75=(a78*a75);
    a75=exp(a75);
    a79=(a10+a75);
    a42=(a42/a79);
    a80=(a42/a79);
    a63=(a63+a80);
    a5=(a5+a63);
    a63=10.;
    a81=arg[1] ? arg[1][17] : 0;
    a63=(a63*a81);
    a82=arg[0] ? arg[0][4] : 0;
    a83=sq(a82);
    a83=(a63*a83);
    a84=arg[0] ? arg[0][5] : 0;
    a85=sq(a84);
    a85=(a81*a85);
    a83=(a83+a85);
    a5=(a5+a83);
    if (res[0]!=0) res[0][0]=a5;
    a14=(a16*a14);
    a17=(a17+a14);
    a14=4.7746482927568596e+00;
    a17=(a14*a17);
    if (res[1]!=0) res[1][0]=a17;
    a19=(a16*a19);
    a15=(a15+a19);
    a14=(a14*a15);
    if (res[1]!=0) res[1][1]=a14;
    a22=(a16*a22);
    a23=(a23+a22);
    a22=6.3661977236758138e-01;
    a22=(a22*a23);
    a22=(a22+a21);
    a16=(a16*a20);
    a22=(a22+a16);
    if (res[1]!=0) res[1][2]=a22;
    a22=(a82+a82);
    a22=(a22*a63);
    if (res[1]!=0) res[1][3]=a22;
    a22=(a84+a84);
    a22=(a22*a81);
    if (res[1]!=0) res[1][4]=a22;
    a65=(a65+a65);
    a80=(a80/a79);
    a42=(a42/a79);
    a42=(a42/a79);
    a80=(a80+a42);
    a75=(a75*a80);
    a78=(a78*a75);
    a66=(a66+a66);
    a78=(a78/a66);
    a68=(a78/a68);
    a65=(a65*a68);
    a46=(a46+a46);
    a62=(a62/a60);
    a61=(a61/a60);
    a61=(a61/a60);
    a62=(a62+a61);
    a56=(a56*a62);
    a59=(a59*a56);
    a47=(a47+a47);
    a59=(a59/a47);
    a49=(a59/a49);
    a46=(a46*a49);
    a65=(a65+a46);
    a24=(a24+a24);
    a44=(a44/a41);
    a43=(a43/a41);
    a43=(a43/a41);
    a44=(a44+a43);
    a36=(a36*a44);
    a40=(a40*a36);
    a25=(a25+a25);
    a40=(a40/a25);
    a28=(a40/a28);
    a24=(a24*a28);
    a65=(a65+a24);
    a2=(a2/a0);
    a65=(a65+a2);
    a4=(a4/a0);
    a4=(a3*a4);
    a65=(a65+a4);
    a65=(-a65);
    if (res[1]!=0) res[1][5]=a65;
    a70=(a70+a70);
    a73=(a78/a73);
    a70=(a70*a73);
    a51=(a51+a51);
    a54=(a59/a54);
    a51=(a51*a54);
    a70=(a70+a51);
    a30=(a30+a30);
    a34=(a40/a34);
    a30=(a30*a34);
    a70=(a70+a30);
    a8=(a8/a0);
    a70=(a70+a8);
    a9=(a9/a0);
    a9=(a3*a9);
    a70=(a70+a9);
    a70=(-a70);
    if (res[1]!=0) res[1][6]=a70;
    a74=(a74+a74);
    a78=(a78/a77);
    a74=(a74*a78);
    a55=(a55+a55);
    a59=(a59/a58);
    a55=(a55*a59);
    a74=(a74+a55);
    a35=(a35+a35);
    a40=(a40/a39);
    a35=(a35*a40);
    a74=(a74+a35);
    a12=(a12/a0);
    a74=(a74+a12);
    a13=(a13/a0);
    a13=(a3*a13);
    a74=(a74+a13);
    a74=(-a74);
    if (res[1]!=0) res[1][7]=a74;
    a6=(a6+a6);
    a6=(a6*a3);
    a6=(-a6);
    if (res[1]!=0) res[1][8]=a6;
    a6=arg[1] ? arg[1][0] : 0;
    a3=(a1/a6);
    a3=(a3+a82);
    if (res[2]!=0) res[2][0]=a3;
    a3=arg[1] ? arg[1][1] : 0;
    a74=(a7/a3);
    a74=(a74+a82);
    if (res[2]!=0) res[2][1]=a74;
    a74=arg[1] ? arg[1][2] : 0;
    a13=(a11/a74);
    a13=(a13+a82);
    if (res[2]!=0) res[2][2]=a13;
    a18=(a1-a18);
    a13=sq(a18);
    a27=(a26+a27);
    a27=sq(a27);
    a13=(a13/a27);
    a29=(a7-a29);
    a82=sq(a29);
    a33=(a32+a33);
    a33=sq(a33);
    a82=(a82/a33);
    a13=(a13+a82);
    a31=(a11-a31);
    a82=sq(a31);
    a38=(a37+a38);
    a38=sq(a38);
    a82=(a82/a38);
    a13=(a13+a82);
    a13=sqrt(a13);
    a82=(a13-a10);
    a82=(a82+a84);
    if (res[2]!=0) res[2][3]=a82;
    a45=(a1-a45);
    a82=sq(a45);
    a48=(a26+a48);
    a48=sq(a48);
    a82=(a82/a48);
    a50=(a7-a50);
    a0=sq(a50);
    a53=(a32+a53);
    a53=sq(a53);
    a0=(a0/a53);
    a82=(a82+a0);
    a52=(a11-a52);
    a0=sq(a52);
    a57=(a37+a57);
    a57=sq(a57);
    a0=(a0/a57);
    a82=(a82+a0);
    a82=sqrt(a82);
    a0=(a82-a10);
    a0=(a0+a84);
    if (res[2]!=0) res[2][4]=a0;
    a1=(a1-a64);
    a64=sq(a1);
    a26=(a26+a67);
    a26=sq(a26);
    a64=(a64/a26);
    a7=(a7-a69);
    a69=sq(a7);
    a32=(a32+a72);
    a32=sq(a32);
    a69=(a69/a32);
    a64=(a64+a69);
    a11=(a11-a71);
    a71=sq(a11);
    a37=(a37+a76);
    a37=sq(a37);
    a71=(a71/a37);
    a64=(a64+a71);
    a64=sqrt(a64);
    a71=(a64-a10);
    a71=(a71+a84);
    if (res[2]!=0) res[2][5]=a71;
    if (res[3]!=0) res[3][0]=a10;
    if (res[3]!=0) res[3][1]=a10;
    if (res[3]!=0) res[3][2]=a10;
    if (res[3]!=0) res[3][3]=a10;
    if (res[3]!=0) res[3][4]=a10;
    if (res[3]!=0) res[3][5]=a10;
    a6=(1./a6);
    if (res[3]!=0) res[3][6]=a6;
    a18=(a18+a18);
    a18=(a18/a27);
    a13=(a13+a13);
    a18=(a18/a13);
    if (res[3]!=0) res[3][7]=a18;
    a45=(a45+a45);
    a45=(a45/a48);
    a82=(a82+a82);
    a45=(a45/a82);
    if (res[3]!=0) res[3][8]=a45;
    a1=(a1+a1);
    a1=(a1/a26);
    a64=(a64+a64);
    a1=(a1/a64);
    if (res[3]!=0) res[3][9]=a1;
    a3=(1./a3);
    if (res[3]!=0) res[3][10]=a3;
    a29=(a29+a29);
    a29=(a29/a33);
    a29=(a29/a13);
    if (res[3]!=0) res[3][11]=a29;
    a50=(a50+a50);
    a50=(a50/a53);
    a50=(a50/a82);
    if (res[3]!=0) res[3][12]=a50;
    a7=(a7+a7);
    a7=(a7/a32);
    a7=(a7/a64);
    if (res[3]!=0) res[3][13]=a7;
    a74=(1./a74);
    if (res[3]!=0) res[3][14]=a74;
    a31=(a31+a31);
    a31=(a31/a38);
    a31=(a31/a13);
    if (res[3]!=0) res[3][15]=a31;
    a52=(a52+a52);
    a52=(a52/a57);
    a52=(a52/a82);
    if (res[3]!=0) res[3][16]=a52;
    a11=(a11+a11);
    a11=(a11/a37);
    a11=(a11/a64);
    if (res[3]!=0) res[3][17]=a11;
    return 0;
}

solver_int32_default FORCESNLPsolver_basic_3_20_50_1_model_20_init(solver_int32_default *f_type, solver_int32_default *n_in, solver_int32_default *n_out, solver_int32_default *sz_arg, solver_int32_default *sz_res) 
{
    *f_type = 1;
    *n_in = 2;
    *n_out = 4;
    *sz_arg = 2;
    *sz_res = 4;
    return 0;
}

solver_int32_default FORCESNLPsolver_basic_3_20_50_1_model_20_sparsity(solver_int32_default i, solver_int32_default *nrow, solver_int32_default *ncol, const solver_int32_default **colind, const solver_int32_default **row) 
{
    const solver_int32_default *s;
    switch (i) 
    {
      case 0:
        s = s0;
        break;
      case 1:
        s = s1;
        break;
      case 2:
        s = s2;
        break;
      case 3:
        s = s3;
        break;
      case 4:
        s = s4;
        break;
      case 5:
        s = s5;
        break;
      default:
        return 1;
    }
    
    *nrow = s[0];
    *ncol = s[1];
    *colind = s + 2;
    *row = s + 2 + (*ncol + 1);
    return 0;
}

solver_int32_default FORCESNLPsolver_basic_3_20_50_1_model_20_work(solver_int32_default *sz_iw, solver_int32_default *sz_w) 
{
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 86;
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
